apiVersion: v2
appVersion: v1.80.0
description: The reference implementation for a Matrix.org chat server
name: synapse
version: 0.14.1
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/matrix-org/synapse
  - https://hub.docker.com/r/matrixdotorg/synapse
  - https://matrix.org/blog/home/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ~12.4.0
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ~17.10.0
    condition: redis.enabled
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update matrixdotorg/synapse docker tag to v1.83.0 ([825f347](https://github.com/halkeye-helm-charts/synapse/commit/825f347f05be17224d4e777b0a05740538a35283))"
  artifacthub.io/images: |
    - name: synapse
      image: "matrixdotorg/synapse:v1.83.0"
