apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "synapse.fullname" . }}-federation-reader
  labels:
{{ include "synapse.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCounts.federation_reader }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{ if eq .Values.strategy.type "Recreate" }}
    rollingUpdate: null
{{- end }}
{{- end }}
  selector:
    matchLabels:
      synapse-component: federation-reader
      app.kubernetes.io/name: {{ include "synapse.name" . }}-federation-reader
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        synapse-component: federation-reader
        app.kubernetes.io/name: {{ include "synapse.name" . }}-federation-reader
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # Avoid co-locating workers with the main Synapse pod if possible
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "synapse.name" . }}
              topologyKey: kubernetes.io/hostname
    {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "synapse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              set -ex
              apk add --no-cache git
              {{- range .Values.extra_python_modules }}
              pip install {{ . }}
              {{- end }}
              chown -R "{{ .Values.settings.uid }}:{{ .Values.settings.gid }}" /data
              /sbin/su-exec "{{ .Values.settings.uid }}:{{ .Values.settings.gid }}" python -m "synapse.app.federation_reader" --config-path "/config/homeserver.yaml" --config-path "/config/federation-reader"
          ports:
            - name: http
              containerPort: {{ (index .Values.federation_reader.worker_listeners 0).port }}
              protocol: TCP
          env:
            - { name: SYNAPSE_CACHE_FACTOR, value: {{ .Values.cacheFactor | toString | quote }} }
          volumeMounts:
            - name: config
              mountPath: /config
          #readinessProbe:
          #  httpGet:
          #    path: /_matrix/client/versions
          #    port: http
          #  initialDelaySeconds: 5
          #  periodSeconds: 2
          #  failureThreshold: 5
          #livenessProbe:
          #  httpGet:
          #    path: /_matrix/client/versions
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "synapse.fullname" . }}
